### ISSUE TITLE
Make top player component

### ISSUE THREAD

**Issue by nikhiljose47** [nikhiljose47/pro-typer#2]

**Comment by nikhiljose47** [comment]
![top-clans](https://user-images.githubusercontent.com/33219597/153920024-bfd0d070-e9a0-4525-ad14-a1d9662f131b.png)

**Comment by Karthik-Vijay** [comment]
<img width="1782" alt="Screenshot 2022-02-15 at 1 26 57 AM" src="https://user-images.githubusercontent.com/55907622/153936907-e59413d6-c935-4f46-b33a-a0d5c1419431.png">
